name: Build Fabric Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (For Gradle to Run)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up JDK 25 (For Minecraft Toolchain)
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.9'

      - name: Build Mod with Gradle
        run: gradle build --no-daemon
